spring:
  application:
    name: commerce
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  config:
    import:
      - classpath:/yml/application-local.yml
  profiles:
    group:
      local: local

toss:
  base-url: https://api.tosspayments.com
  secret-key: ${TOSS_SECRET_KEY:}

payment:
  kafka:
    topic:
      completed: payment.completed
