spring:
  application:
    name: commerce
  config:
    import:
      - classpath:/yml/application-local.yml
  profiles:
    group:
      local: local

toss:
  base-url: https://api.tosspayments.com
  secret-key: ${TOSS_SECRET_KEY:}
