spring:
  config:
    activate:
      on-profile: local
    import: optional:file:.env[.properties]

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

  datasource:
    url: jdbc:mysql://${DB_LOCAL_HOST}:${DB_LOCALHOST_PORT}/${DB_DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
    hikari:
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${REDIS_LOCAL_HOST:localhost}
      port: ${REDIS_LOCAL_PORT:6379}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiry: 1800000
    refresh-token-expiry: 1209600000

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    org.springframework.web: INFO
    root: INFO
    com.mist.commerce: DEBUG
    org.hibernate.SQL: DEBUG
